on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./public

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./public
      - name: Deploy to Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: 2023.protocol.berlin
#      - uses: aquiladev/ipfs-action@v0.3.1
#        name: Upload to Pinata
#        with:
#          path: ./public
#          pinName: ipns.protocol.berlin.${{ github.sha }}
#          service: pinata
#          pinataKey: ${{ secrets.PINATA_KEY }}
#          pinataSecret: ${{ secrets.PINATA_SECRET }}
#      - uses: aquiladev/ipfs-action@v0.3.1
#        name: Upload to Infura
#        with:
#          path: ./public
#          pinName: ipns.protocol.berlin.${{ github.sha }}
#          service: infura
#          infuraProjectId: ${{ secrets.INFURA_ID }}
#          infuraProjectSecret: ${{ secrets.INFURA_SECRET }}
